//WACP TO FIND FACTORAIL OF A NUMBER USING RECURSION
// WACP TO FIND FIBONAKI NUMBER USING RECURTION
// WACP TO COMPLY TO COMPLY TO ALL PARAMETERS
//     A. WITHOUT RETURNTYPE WITHOUT PARAMETERS
//     B. WITHOUT RETURNTYPE WITH PARAMETERS
//     C. WITH RETURNTYPE WITHOUT PARAMETERS
//     D. WITH RETURNTYPE WITH PARAMETERS
// WACP TO FIND HCF AND LCM OF 2 NUMBERS USING FUNCTION
// WACP TO SWAP 2 NUMBERS USING CALL BY REFERENCE AND CALL BY VALUE
#include <stdio.h>
int sum(int a, int b)
{
    return a+b;
}
int main()
{
    int c;
    c = sum(5,1);
    printf("%d",c);
    return 0;
}